services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: elt_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dagster:
    build:
      context: .
      dockerfile: Dockerfile.dagster
    volumes:
      - ./dagster_project:/opt/dagster/app
    ports:
      - "3000:3000"  # Port pour le webserver Dagster
    environment:
      DAGSTER_POSTGRES_HOST: postgres
      DAGSTER_POSTGRES_DB: elt_db
      DAGSTER_POSTGRES_USER: user
      DAGSTER_POSTGRES_PASSWORD: password
    depends_on:
      - postgres

  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dbt
    volumes:
      - ./dbt_project:/usr/app/dbt_project
    working_dir: /usr/app/dbt_project
    depends_on:
      - postgres

volumes:
  postgres_data:
