FROM python:3.11-slim

WORKDIR /usr/app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

# Install dbt
RUN pip install --upgrade pip
RUN pip install dbt-postgres

# Default command
CMD ["tail", "-f", "/dev/null"]
