version: 2

models:
  - name: match_transforms
    description: "Transformations enrichies avec score décomposé, pronostic et traductions"
    columns:
      - name: pronostic
        description: "Résultat du pronostic basé sur les cotes"
